version: '3.6'

services:

  nginx:
    image: 'nginx:stable'
    ports:
      - '8080:80'
    depends_on:
      - php

  php:
    image: 'php:7.3-fpm'

  php-cli:
    image: 'php:7.3-cli'
    working_dir: '/usr/src/myapp'
    volumes:
      - './:/usr/src/myapp'

  composer:
    image: composer
    volumes:
      - './:/app'
      - '/tmp:/tmp'
